# Use the official Node.js image
FROM node:20

# Set the working directory inside the container
WORKDIR /usr/src/app

# Install dependencies
COPY server/package*.json ./
RUN npm install

# Copy the rest of the server files
COPY server/ .

# Expose the application port
EXPOSE 5000

# Command to run your app
CMD ["npm", "start"]
